import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen container px-6 max-w-7xl mx-auto flex flex-col justify-between itmes-center`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
